services:
  app:
    build:
      context: .
    container_name: rentacar-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - rentacar-net
    depends_on:
      - db

  web:
    image: nginx:stable
    container_name: rentacar-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rentacar-net
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: rentacar-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rentacar-app
      MYSQL_DATABASE: rentacar_app
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - rentacar-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rentacar-pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - rentacar-net
    depends_on:
      - db

volumes:
  dbdata:

networks:
  rentacar-net:
    driver: bridge
